name: video
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # camerawesome: ^2.1.0
  camera: ^0.11.0+2
  # flutter_riverpod: ^2.6.1
  http: ^1.2.2
  shared_preferences: ^2.3.5
  video_player: ^2.9.2
  path_provider: ^2.1.5
  flick_video_player: ^0.9.0
  chewie: ^1.9.2
  flutter_native_splash: ^2.4.4
  video_compress: ^3.1.4
  flutter_riverpod: ^2.6.1

  # flick_video_player: ^0.9.0
  # video_compress: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  image: assets/icon.jpg
  color: "#ffffff"
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.jpg
    - assets/4.jpg
    - assets/7.jpg
    - assets/9.jpg
